services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis

volumes:
  redis_data:
